[env:m5stick-c-plus]
platform = espressif32
board = m5stick-c
framework = arduino
board_build.mcu = esp32
board_build.f_cpu = 240000000
board_build.flash_mode = qio
board_build.flash_size = 4MB
board_build.partitions = default.csv

lib_deps =
    m5stack/M5StickCPlus@^0.1.1

monitor_speed = 115200
upload_speed = 1500000

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM

